import { useEffect, useMemo, useState } from 'react'
import { supabase } from './supabaseClient'
import Header from './components/Header'
import Navigation from './components/Navigation'
import AuthScreen from './components/AuthScreen'
import FocusOverlay from './components/FocusOverlay'
import CommandCenter from './components/CommandCenter'
import CareerRoadmap from './components/CareerRoadmap'
import Portfolio from './components/Portfolio'
import WeeklyReview from './components/WeeklyReview'
import DebugCenter from './components/DebugCenter'
import Settings from './components/Settings'
import { careerItems,getCareerMissingItems,getCareerReadiness,getNextCareerItem } from './data/careerRoadmap'
import { getTimelineActiveStage } from './data/timeline'
import { createOrders,getWeeklyReview } from './utils/dailyOrders'
import { applyXP,defaultProfile,energyFromSleep } from './utils/progressEngine'
import { getPrayerWindow,getTimeState,todayKey } from './utils/timeEngine'
import { loadPrayerEvents,savePrayerEvent } from './services/prayerService'
import { enableNotifications as requestNotifications } from './services/notificationService'
if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{})}
export default function App(){
const[session,setSession]=useState(null),[authMode,setAuthMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[loading,setLoading]=useState(true),[cloudReady,setCloudReady]=useState(false),[profile,setProfile]=useState(defaultProfile),[sleepHours,setSleepHours]=useState(5),[completedOrders,setCompletedOrders]=useState({}),[prayerStatus,setPrayerStatus]=useState({}),[completedCareer,setCompletedCareer]=useState([]),[toast,setToast]=useState(''),[now,setNow]=useState(new Date()),[view,setView]=useState('command'),[focusActive,setFocusActive]=useState(false),[focusSeconds,setFocusSeconds]=useState(1500),[focusTask,setFocusTask]=useState('جلسة تركيز')
const timeState=useMemo(()=>getTimeState(now),[now]),prayerWindow=useMemo(()=>getPrayerWindow(now),[now]),careerReadiness=useMemo(()=>getCareerReadiness(completedCareer),[completedCareer]),adjustedEnergy=energyFromSleep(sleepHours),readiness=Math.round((profile.momentum+adjustedEnergy+profile.focus+profile.professionalValue)/4),nextCareerItem=useMemo(()=>getNextCareerItem(completedCareer),[completedCareer]),missingCareerItems=useMemo(()=>getCareerMissingItems(completedCareer),[completedCareer]),activeTimelineStage=useMemo(()=>getTimelineActiveStage(careerReadiness),[careerReadiness]),todayOrders=useMemo(()=>createOrders({timeState,readiness,careerReadiness,prayerWindow,nextCareerItem}),[timeState,readiness,careerReadiness,prayerWindow,nextCareerItem]),weeklyReview=useMemo(()=>getWeeklyReview({completedCareer,completedOrders,readiness,careerReadiness,profile,careerItems}),[completedCareer,completedOrders,readiness,careerReadiness,profile]),xpNeed=500+profile.level*120,xpPercent=Math.min(100,Math.round(profile.xp/xpNeed*100))
useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[])
useEffect(()=>{if(!focusActive)return;const t=setInterval(()=>setFocusSeconds(p=>{if(p<=1){clearInterval(t);setFocusActive(false);addXP(60,focusTask);notify('تمت جلسة التركيز');return 1500}return p-1}),1000);return()=>clearInterval(t)},[focusActive,focusTask])
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);setLoading(false)});return()=>l.subscription.unsubscribe()},[])
useEffect(()=>{if(session?.user)loadCloudData()},[session])
useEffect(()=>{if(session?.user&&cloudReady)saveCloud()},[profile,sleepHours,completedOrders,completedCareer])
function notify(x){setToast(x);setTimeout(()=>setToast(''),2200)}
async function signIn(e){e.preventDefault();const r=authMode==='signup'?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});r.error?notify(r.error.message):notify(authMode==='signup'?'تم إنشاء الحساب':'تم الدخول')}
async function signOut(){await supabase.auth.signOut()}
async function loadCloudData(){setCloudReady(false);const user=(await supabase.auth.getUser()).data.user;if(!user)return;setPrayerStatus(await loadPrayerEvents(user.id));let{data:p}=await supabase.from('ascend_profiles').select('*').eq('id',user.id).maybeSingle();if(!p){const{data:c}=await supabase.from('ascend_profiles').insert({id:user.id,name:'مصعب'}).select().single();p=c}if(p)setProfile({name:p.name||'مصعب',level:p.level??1,xp:p.xp??0,phase:p.phase||'مرحلة التأسيس',momentum:p.momentum??55,focus:p.focus??50,energy:p.energy??50,professionalValue:p.professional_value??5});const{data:log}=await supabase.from('ascend_daily_logs').select('*').eq('user_id',user.id).eq('log_date',todayKey()).maybeSingle();if(log){setSleepHours(Number(log.sleep_hours??5));setCompletedOrders(log.completed_orders||{})}else await supabase.from('ascend_daily_logs').insert({user_id:user.id,log_date:todayKey(),sleep_hours:5,readiness:50,current_prayer:prayerWindow.current.key,orders:todayOrders,completed_orders:{},daily_state:timeState.key});const{data:career}=await supabase.from('ascend_career_progress').select('item_id').eq('user_id',user.id);setCompletedCareer((career||[]).map(x=>x.item_id));setCloudReady(true)}
async function saveCloud(){const user=(await supabase.auth.getUser()).data.user;if(!user)return;await supabase.from('ascend_profiles').upsert({id:user.id,name:profile.name,level:profile.level,xp:profile.xp,phase:profile.phase,momentum:profile.momentum,focus:profile.focus,energy:profile.energy,professional_value:profile.professionalValue,updated_at:new Date().toISOString()});await supabase.from('ascend_daily_logs').upsert({user_id:user.id,log_date:todayKey(),sleep_hours:sleepHours,readiness,current_prayer:prayerWindow.current.key,orders:todayOrders,completed_orders:completedOrders,daily_state:timeState.key,updated_at:new Date().toISOString()},{onConflict:'user_id,log_date'})}
function addXP(a,l){setProfile(p=>applyXP(p,a,l))}
async function confirmCurrentPrayer(){const key=prayerWindow.current.key,label=prayerWindow.current.label,next={...(prayerStatus||{}),[key]:true};setPrayerStatus(next);setProfile(p=>({...p,momentum:Math.min(100,p.momentum+3)}));const user=(await supabase.auth.getUser()).data.user;if(user){const ok=await savePrayerEvent(user.id,key,label);if(ok)setPrayerStatus(await loadPrayerEvents(user.id))}notify(`تم تسجيل صلاة ${label}`)}
function completeOrder(o){if(completedOrders[o.id])return;setCompletedOrders(p=>({...p,[o.id]:true}));if(o.type!=='prayer'){addXP(o.xp,o.title);notify(`تم تنفيذ الأمر: ${o.title}`)}else confirmCurrentPrayer()}
function startFocus(o,m=25){setFocusTask(o?.title||'جلسة تركيز');setFocusSeconds(m*60);setFocusActive(true)}
function stopFocus(){setFocusActive(false);setFocusSeconds(1500)}
async function enableNotifications(){const r=await requestNotifications();notify(r.message)}
async function completeCareerItem(item){if(completedCareer.includes(item.id))return;setCompletedCareer(p=>[...p,item.id]);const user=(await supabase.auth.getUser()).data.user;if(user)await supabase.from('ascend_career_progress').insert({user_id:user.id,item_id:item.id,item_type:item.type});addXP(item.type==='project'?300:120,item.title);notify(`تم إنجاز: ${item.title}`)}
async function resetTestData(){if(!window.confirm('سيتم مسح تقدم التجربة والرجوع للبداية. هل أنت متأكد؟'))return;setProfile(defaultProfile);setSleepHours(5);setCompletedOrders({});setPrayerStatus({});setCompletedCareer([]);setFocusActive(false);const user=(await supabase.auth.getUser()).data.user;if(user){await supabase.from('ascend_profiles').upsert({id:user.id,name:'مصعب',level:1,xp:0,phase:'مرحلة التأسيس',momentum:55,focus:50,energy:50,professional_value:5,updated_at:new Date().toISOString()});await supabase.from('ascend_daily_logs').upsert({user_id:user.id,log_date:todayKey(),sleep_hours:5,readiness:50,current_prayer:prayerWindow.current.key,orders:todayOrders,completed_orders:{},daily_state:timeState.key,updated_at:new Date().toISOString()},{onConflict:'user_id,log_date'});await supabase.from('ascend_career_progress').delete().eq('user_id',user.id);await supabase.from('ascend_prayer_events').delete().eq('user_id',user.id).eq('prayer_date',todayKey())}notify('تم تصفير بيانات التجربة')}
if(loading)return <main className="auth-screen"><div className="auth-card"><div className="logo">A</div><h1>Ascend</h1><p>جاري التحميل...</p></div></main>
if(!session)return <AuthScreen email={email} setEmail={setEmail} password={password} setPassword={setPassword} authMode={authMode} setAuthMode={setAuthMode} onSubmit={signIn} toast={toast}/>
return <main className={'app state-'+timeState.key}>{toast&&<div className="toast">{toast}</div>}<FocusOverlay active={focusActive} task={focusTask} seconds={focusSeconds} onStop={stopFocus}/><Header profile={profile} now={now} cloudReady={cloudReady} onSignOut={signOut}/><Navigation view={view} setView={setView}/>{view==='command'&&<CommandCenter timeState={timeState} readiness={readiness} adjustedEnergy={adjustedEnergy} careerReadiness={careerReadiness} profile={profile} xpPercent={xpPercent} xpNeed={xpNeed} prayerWindow={prayerWindow} prayerStatus={prayerStatus} confirmPrayer={confirmCurrentPrayer} todayOrders={todayOrders} completedOrders={completedOrders} completeOrder={completeOrder} startFocus={startFocus} enableNotifications={enableNotifications}/>} {view==='career'&&<CareerRoadmap careerReadiness={careerReadiness} missingCareerItems={missingCareerItems} activeTimelineStage={activeTimelineStage} completedCareer={completedCareer} completeCareerItem={completeCareerItem}/>} {view==='portfolio'&&<Portfolio completedCareer={completedCareer}/>} {view==='review'&&<WeeklyReview weeklyReview={weeklyReview}/>} {view==='debug'&&<DebugCenter cloudReady={cloudReady} prayerStatus={prayerStatus} prayerWindow={prayerWindow} completedOrders={completedOrders} completedCareer={completedCareer}/>} {view==='settings'&&<Settings adjustedEnergy={adjustedEnergy} sleepHours={sleepHours} setSleepHours={setSleepHours} readiness={readiness} resetTestData={resetTestData} prayerStatus={prayerStatus} prayerWindow={prayerWindow}/>}</main>
}
