export const prayerTimes={fajr:'04:25',dhuhr:'12:15',asr:'15:35',maghrib:'18:55',isha:'20:25'}
export const prayerLabels={fajr:'الفجر',dhuhr:'الظهر',asr:'العصر',maghrib:'المغرب',isha:'العشاء'}
export function todayKey(){return new Date().toISOString().slice(0,10)}
export function formatTime(d){return d.toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}
export function formatDate(d){return d.toLocaleDateString('ar-SA',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
export function secondsText(s){const m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
function tmin(v){const [h,m]=v.split(':').map(Number);return h*60+m}
export function getPrayerWindow(date){const now=date.getHours()*60+date.getMinutes();const e=Object.entries(prayerTimes).map(([key,time])=>({key,label:prayerLabels[key],minutes:tmin(time),time}));let current=e[0];for(const p of e){if(p.minutes<=now)current=p}let next=e.find(p=>p.minutes>now),tom=false;if(!next){next=e[0];tom=true}const nextDiff=tom?(1440-now)+next.minutes:next.minutes-now;const currentEnds=next.minutes>current.minutes?next.minutes:1440+next.minutes;const currentDiff=currentEnds-now;return{current,next,nextDiff,currentDiff,nextText:`${Math.floor(nextDiff/60)}س ${nextDiff%60}د`,currentText:`${Math.floor(currentDiff/60)}س ${currentDiff%60}د`}}
export function getTimeState(date){const h=date.getHours()+date.getMinutes()/60;if(h>=2&&h<7)return{key:'sleep',title:'وضع النوم',priority:'الراحة وحماية طاقة الغد'};if(h>=7&&h<8)return{key:'activation',title:'تشغيل اليوم',priority:'تهيئة الطاقة'};if(h>=8&&h<10.5)return{key:'deep',title:'نافذة التركيز العميق',priority:'المهمة المهنية الرئيسية'};if(h>=10.5&&h<13)return{key:'transition',title:'انتقال وتجهيز',priority:'مراجعة خفيفة واستعداد'};if(h>=13&&h<22)return{key:'work',title:'وضع الدوام',priority:'حفظ الزخم بدون ضغط'};if(h>=22&&h<24)return{key:'evening',title:'استعادة بعد الدوام',priority:'مراجعة خفيفة أو استعادة'};return{key:'shutdown',title:'إغلاق اليوم',priority:'النوم وعدم فتح مهام ثقيلة'}}
